name: Lint

on: [push, pull_request]

jobs:
  black:
    name: Check formatting with Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "--check --verbose --diff"
          src: "./atuin_graph"
  ruff:
    name: Lint code with Ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: pip install ruff
      - run: ruff --format=github .
